name: flutter_bloc_login_firebase
description: Working login and signup with Bloc pattern using Firebase.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^0.1.2
  firebase_auth: 
  google_sign_in: 
  flutter_bloc: ^4.0.1
  equatable:
  meta:
  rxdart:
  flutter_auth_buttons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
